allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(":app")

    plugins.withId("com.android.library") {
        def androidExtension = project.extensions.findByName("android")
        if (androidExtension != null && androidExtension.namespace == null) {
            androidExtension.namespace = project.group.toString()
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
